"""empty message

Revision ID: 03d744f8b1af
Revises: 
Create Date: 2017-10-17 16:37:39.122421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03d744f8b1af'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modules',
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('rooms',
    sa.Column('door_id', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('door_id')
    )
    op.create_table('users',
    sa.Column('ivle_id', sa.String(length=9), nullable=False),
    sa.PrimaryKeyConstraint('ivle_id')
    )
    op.create_table('enrolments',
    sa.Column('user_ivle_id', sa.String(length=9), nullable=False),
    sa.Column('module_code', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['module_code'], ['modules.code'], ),
    sa.ForeignKeyConstraint(['user_ivle_id'], ['users.ivle_id'], ),
    sa.PrimaryKeyConstraint('user_ivle_id', 'module_code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enrolments')
    op.drop_table('users')
    op.drop_table('rooms')
    op.drop_table('modules')
    # ### end Alembic commands ###
