"""empty message

Revision ID: 357a7a3e96a6
Revises: 03d744f8b1af
Create Date: 2017-10-17 16:38:40.397105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '357a7a3e96a6'
down_revision = '03d744f8b1af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room_accesses',
    sa.Column('module_code', sa.String(length=16), nullable=False),
    sa.Column('room_door_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['module_code'], ['modules.code'], ),
    sa.ForeignKeyConstraint(['room_door_id'], ['rooms.door_id'], ),
    sa.PrimaryKeyConstraint('module_code', 'room_door_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('room_accesses')
    # ### end Alembic commands ###
