"""empty message

Revision ID: 5cf93249da4c
Revises: 357a7a3e96a6
Create Date: 2017-10-18 14:09:05.428523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cf93249da4c'
down_revision = '357a7a3e96a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('secret_key', sa.String(length=64), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'secret_key')
    # ### end Alembic commands ###
